# Generated by Django 4.2.7 on 2025-09-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('realtor', 'Риелтор'), ('superadmin', 'Супер-администратор')], default='client', max_length=15, verbose_name='Роль'),
        ),
    ]
